import { before,after,test } from 'node:test';
import assert from 'node:assert/strict';
import { Pool } from 'pg';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
const {createApp}=require('../dist/main');
const config={host:path.resolve(__dirname,'../../.local/postgres/socket'),port:55438,database:'school_saas_local'};
const owner=new Pool({...config,user:process.env.USER}),runtime=new Pool({...config,user:'school_app'});
const school=randomUUID(),other=randomUUID(),year=randomUUID(),nurseryClass=randomUUID(),kgClass=randomUUID(),headMember=randomUUID(),teacherMember=randomUUID(),guardianMember=randomUUID();
const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Africa/Accra'}),shift=(days:number)=>new Date(Date.parse(`${today}T00:00:00Z`)+days*86400000).toISOString().slice(0,10);
let app:any,base:string,head:any,teacher:any,guardian:any,desk:any,nurseryLearner:string,nurseryEnrolment:string,kgLearner:string,kgEnrolment:string,nurseryPolicy:any,kgPolicy:any,nurseryPolicySpec:any,kgPolicySpec:any;
async function login(email:string){const response=await fetch(`${base}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:'Synthetic-only-2026!'})});assert.equal(response.status,201);return {cookie:response.headers.get('set-cookie')!.split(';')[0],csrf:(await response.json()).csrfToken};}
function call(route:string,method='GET',body?:unknown,actor=head,target=school){return fetch(`${base}/schools/${target}${route}`,{method,headers:{cookie:actor.cookie,'content-type':'application/json','x-csrf-token':actor.csrf},...(body?{body:JSON.stringify(body)}:{})});}
async function post(route:string,body:Record<string,unknown>,status=201,actor=head,target=school){const response=await call(route,'POST',{operationId:randomUUID(),...body},actor,target),value=await response.json();assert.equal(response.status,status,JSON.stringify(value));return value;}
function policy(level:'Nursery'|'KG',sourceReference:string){return {level,title:`School ${level} observation guide`,sourceKind:'school_local',sourceIssuer:'School learning team',sourceReference,sourceVersion:'2026-1',effectiveStart:shift(-10),indicators:[{code:'AREA-01',title:'Participates in shared activity',learningArea:'Communication',strand:'Interaction',subStrand:'Shared activity',descriptors:[{id:randomUUID(),text:'Joins a shared activity with a peer'},{id:randomUUID(),text:'Takes a turn during a shared activity'}]}],...(level==='Nursery'?{specialistName:'Synthetic specialist reviewer',specialistQualification:'Early childhood development specialist',specialistReviewReference:'School review minute 1',specialistReviewedOn:shift(-12)}:{})};}
before(async()=>{
  process.env.DEV_AUTH='synthetic-local';app=await createApp();await app.listen(0,'127.0.0.1');base=`${await app.getUrl()}/api/v1`;[head,teacher,guardian,desk]=await Promise.all(['head@example.test','teacher@example.test','guardian@example.test','frontdesk@example.test'].map(login));
  await owner.query('INSERT INTO schools(id,name) VALUES($1,$2),($3,$4)',[school,'Synthetic early years school',other,'Other early years school']);
  await owner.query("INSERT INTO memberships(id,school_id,user_id,role) VALUES($1,$2,'20000000-0000-4000-8000-000000000001','headteacher'),($3,$2,'20000000-0000-4000-8000-000000000002','teacher'),($4,$2,'20000000-0000-4000-8000-000000000004','frontdesk'),($5,$2,'20000000-0000-4000-8000-000000000003','guardian')",[headMember,school,teacherMember,randomUUID(),guardianMember]);
  await owner.query("INSERT INTO academic_years(id,school_id,name,start_date,end_date) VALUES($1,$2,'Early years synthetic year',$3,$4)",[year,school,shift(-50),shift(100)]);
  await owner.query("INSERT INTO class_sections(id,school_id,academic_year_id,name,level,capacity) VALUES($1,$2,$3,'Nursery Blue','Nursery',20),($4,$2,$3,'KG Green','KG',20)",[nurseryClass,school,year,kgClass]);
  await owner.query('INSERT INTO teaching_assignments(id,school_id,class_id,teacher_membership_id,teacher_display_name,start_date,end_date,grant_reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),school,nurseryClass,teacherMember,'Kofi Sample',shift(-5),shift(30),'Reviewed synthetic Nursery teaching assignment',headMember]);
  for(const [level,classId,key] of [['Nursery',nurseryClass,'nursery'],['KG',kgClass,'kg']] as const){const learner=randomUUID(),enrolment=randomUUID();await owner.query('INSERT INTO learners(id,school_id,admission_number,full_name) VALUES($1,$2,$3,$4)',[learner,school,`EY-${learner.slice(0,8)}`,`${level} synthetic learner`]);await owner.query('INSERT INTO enrolments(id,school_id,learner_id,class_id,start_date) VALUES($1,$2,$3,$4,$5)',[enrolment,school,learner,classId,shift(-10)]);if(key==='nursery'){nurseryLearner=learner;nurseryEnrolment=enrolment;}else{kgLearner=learner;kgEnrolment=enrolment;}}
});
after(async()=>{await app?.close();await owner.end();await runtime.end();});
test('early-years tables force RLS and expose nothing without school context',async()=>{for(const table of ['early_years_policies','early_years_indicators','early_years_observations']){assert.equal((await runtime.query(`SELECT * FROM ${table}`)).rowCount,0);assert.equal((await runtime.query('SELECT relforcerowsecurity FROM pg_class WHERE relname=$1',[table])).rows[0].relforcerowsecurity,true);}});
test('Nursery and KG policies stay separate and Nursery review evidence is required',async()=>{
  const futureReview=policy('Nursery','Future specialist review');futureReview.effectiveStart=shift(5);futureReview.specialistReviewedOn=shift(2);await post('/early-years/policies',futureReview,400);
  const nurseryBody=policy('Nursery','Local Nursery guide, school supplied');nurseryPolicySpec=nurseryBody;await post('/early-years/policies',{...nurseryBody,specialistName:undefined},400);await post('/early-years/policies',nurseryBody,403,teacher);nurseryPolicy=await post('/early-years/policies',nurseryBody);await post(`/early-years/policies/${nurseryPolicy.id}/approve`,{version:1},403,teacher);nurseryPolicy=await post(`/early-years/policies/${nurseryPolicy.id}/approve`,{version:1});const overlap=await post('/early-years/policies',policy('Nursery','Second overlapping Nursery guide'));await post(`/early-years/policies/${overlap.id}/approve`,{version:1},409);
  kgPolicySpec=policy('KG','Local KG guide, school supplied');kgPolicy=await post('/early-years/policies',kgPolicySpec);kgPolicy=await post(`/early-years/policies/${kgPolicy.id}/approve`,{version:1});
  await assert.rejects(owner.query('UPDATE early_years_policies SET title=$1 WHERE school_id=$2 AND id=$3',['Changed approved policy title',school,nurseryPolicy.id]),/Early-years policy history is immutable/);
  await assert.rejects(owner.query('INSERT INTO early_years_indicators(id,school_id,policy_id,code,title,learning_area,strand,sub_strand,descriptors) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),school,nurseryPolicy.id,'EXTRA','Unapproved change','Area','Strand','Sub-strand',JSON.stringify([{id:randomUUID(),text:'Synthetic descriptor'}])]),/Indicators can only be added to draft policies/);
  const history=await (await call('/early-years/policies?level=Nursery')).json();assert.equal(history.items.length,2);assert.ok(history.items.some((item:any)=>item.id===nurseryPolicy.id&&item.level==='Nursery'&&item.status==='approved'&&item.indicators.length===1&&/school review/i.test(item.specialist_review_reference)));
  assert.equal((await call('/early-years/policies?level=KG','GET',undefined,desk)).status,403);assert.equal((await call('/early-years/policies?level=Nursery','GET',undefined,head,other)).status,404);
});
test('teacher records only evidence-backed assigned-class observations and retains correction history',async()=>{
  const nurseryIndicator=nurseryPolicySpec.indicators[0],nurseryDescriptor=nurseryIndicator.descriptors[0];
  const classes=await (await call('/early-years/classes?level=Nursery','GET',undefined,teacher)).json();assert.deepEqual(classes.items.map((item:any)=>item.id),[nurseryClass]);
  await post(`/early-years/classes/${nurseryClass}/observations`,{learnerId:nurseryLearner,enrolmentId:nurseryEnrolment,observedOn:today,policyId:kgPolicy.id,entries:[{indicatorId:randomUUID(),status:'observed',descriptorId:randomUUID(),evidence:'Observed synthetic evidence'}]},400,teacher);
  const body={learnerId:nurseryLearner,enrolmentId:nurseryEnrolment,observedOn:today,policyId:nurseryPolicy.id,entries:[{indicatorId:(await owner.query('SELECT id FROM early_years_indicators WHERE policy_id=$1',[nurseryPolicy.id])).rows[0].id,status:'observed',descriptorId:nurseryDescriptor.id,evidence:'Joined a shared activity and waited for a peer to finish.'}]};
  await post(`/early-years/classes/${nurseryClass}/observations`,{...body,observedOn:shift(-8)},404,teacher);await post(`/early-years/classes/${nurseryClass}/observations`,{...body,observedOn:shift(1)},400,teacher);
  await post(`/early-years/classes/${nurseryClass}/observations`,{...body,entries:[{...body.entries[0],evidence:undefined}]},400,teacher);
  await post(`/early-years/classes/${nurseryClass}/observations`,{...body,entries:[{indicatorId:body.entries[0].indicatorId,status:'not_observed',descriptorId:nurseryDescriptor.id}]},400,teacher);
  const created=await post(`/early-years/classes/${nurseryClass}/observations`,body,201,teacher);assert.equal(created.level,'Nursery');
  assert.equal((await (await call(`/early-years/observations?learnerId=${nurseryLearner}`,'GET',undefined,teacher)).json()).total,1);
  const correction={version:1,correctionReason:'Teacher clarified the written observation evidence',entries:[{indicatorId:body.entries[0].indicatorId,status:'observed',descriptorId:nurseryIndicator.descriptors[1].id,evidence:'Took a turn during the shared activity after a verbal prompt.'}]};
  const race=await Promise.all([1,2].map(()=>call(`/early-years/observations/${created.id}/correct`,'POST',{operationId:randomUUID(),...correction},teacher)));assert.deepEqual(race.map(r=>r.status).sort(),[201,409]);const corrected=await race.find(r=>r.status===201)!.json();assert.equal(corrected.version,2);assert.equal(corrected.supersedesId,created.id);
  await post(`/early-years/observations/${created.id}/correct`,{version:1,correctionReason:'Stale correction must be rejected',entries:body.entries},409,teacher);
  await owner.query("UPDATE teaching_assignments SET revoked_at=now(),revoked_by=$1,revocation_reason='Synthetic early-years grant revoked' WHERE school_id=$2 AND class_id=$3",[headMember,school,nurseryClass]);
  await post(`/early-years/observations/${corrected.id}/correct`,{version:2,correctionReason:'Revoked educator correction must be rejected',entries:body.entries},404,teacher);
  const headCorrection=await post(`/early-years/observations/${corrected.id}/correct`,{version:2,correctionReason:'Headteacher reviewed correction after educator grant ended',entries:body.entries},201,head);assert.equal(headCorrection.version,3);
  assert.equal((await (await call(`/early-years/observations?learnerId=${nurseryLearner}`,'GET',undefined,teacher)).json()).total,0);const history=await (await call(`/early-years/observations?learnerId=${nurseryLearner}`,'GET',undefined,head)).json();assert.equal(history.total,3);assert.equal(history.items[0].supersedes_id,corrected.id);assert.equal(history.items[0].recorded_by_membership_id,headMember);assert.equal(history.items[0].is_current,true);assert.equal(history.items[1].recorded_by_membership_id,teacherMember);assert.equal(history.items[1].is_current,false);assert.equal(history.items[2].entries[0].evidence,body.entries[0].evidence);const oldest=await (await call(`/early-years/observations?learnerId=${nurseryLearner}&limit=1&offset=2`,'GET',undefined,head)).json();assert.equal(oldest.items[0].is_current,false);
  const kgId=(await owner.query('SELECT id FROM early_years_indicators WHERE policy_id=$1',[kgPolicy.id])).rows[0].id;await post(`/early-years/classes/${kgClass}/observations`,{learnerId:kgLearner,enrolmentId:kgEnrolment,observedOn:today,policyId:nurseryPolicy.id,entries:[{indicatorId:kgId,status:'not_observed'}]},400,head);
  await post(`/early-years/classes/${kgClass}/observations`,{learnerId:kgLearner,enrolmentId:kgEnrolment,observedOn:shift(1),policyId:kgPolicy.id,entries:[{indicatorId:kgId,status:'not_observed'}]},400,head);
  assert.equal((await call(`/early-years/classes/${kgClass}/observations`,'POST',{operationId:randomUUID(),learnerId:nurseryLearner,enrolmentId:nurseryEnrolment,observedOn:today,policyId:nurseryPolicy.id,entries:[{indicatorId:body.entries[0].indicatorId,status:'not_observed'}]},teacher)).status,404);
  assert.equal((await call(`/early-years/observations/${created.id}/correct`,'POST',{operationId:randomUUID(),version:1,correctionReason:'Desk must not access observations',entries:body.entries},desk)).status,403);
  nurseryPolicy=await post(`/early-years/policies/${nurseryPolicy.id}/retire`,{version:2,reason:'School replaced this synthetic indicator guide'});assert.equal(nurseryPolicy.status,'retired');assert.equal((await call(`/early-years/observations?learnerId=${nurseryLearner}`,'GET',undefined,teacher)).status,200);
  await post(`/early-years/classes/${nurseryClass}/observations`,body,400,head);
});

test('narrative reports require review, reset stale approval, retain history and expose only published versions to guardians',async()=>{
  const linkId=randomUUID();await owner.query("INSERT INTO guardian_links(id,school_id,learner_id,guardian_membership_id,guardian_display_name,academic,billing,pickup,contact,verified_at,verified_by,verification_reason) VALUES($1,$2,$3,$4,'Abena Sample',true,false,false,false,now(),$5,'Synthetic academic access verified for report test')",[linkId,school,nurseryLearner,guardianMember,headMember]);
  const created=await post('/early-years/reports',{learnerId:nurseryLearner,enrolmentId:nurseryEnrolment,periodStart:today,periodEnd:today,strengths:'Joined a shared activity and took turns with peers.',nextSteps:'Continue offering opportunities to lead a short shared activity.',teacherNote:'Synthetic teacher note'});
  assert.equal(created.status,'draft');
  assert.equal((await call('/early-years/reports?limit=10','GET',undefined,desk)).status,403);
  assert.equal((await call(`/guardian/children/${nurseryLearner}/reports`,'GET',undefined,guardian)).status,200);
  const submitted=await post(`/early-years/report-revisions/${created.revisionId}/submit`,{version:1});assert.equal(submitted.status,'submitted');
  const approved=await post(`/early-years/report-revisions/${created.revisionId}/approve`,{version:2});assert.equal(approved.status,'approved');
  const oldObservation=(await owner.query("SELECT id,version,entries FROM early_years_observations WHERE school_id=$1 AND learner_id=$2 AND NOT EXISTS(SELECT 1 FROM early_years_observations n WHERE n.school_id=early_years_observations.school_id AND n.supersedes_id=early_years_observations.id) ORDER BY created_at DESC LIMIT 1",[school,nurseryLearner])).rows[0];
  const correctedEntries=oldObservation.entries.map((entry:any)=>({indicatorId:entry.indicatorId,status:entry.status,...(entry.status==='observed'?{descriptorId:entry.descriptor.id,evidence:`${entry.evidence} Clarified after report approval.`}:{})}));
  await post(`/early-years/observations/${oldObservation.id}/correct`,{version:oldObservation.version,correctionReason:'Headteacher clarified evidence after report approval',entries:correctedEntries});
  const invalidated=await post(`/early-years/report-revisions/${created.revisionId}/publish`,{version:approved.version});assert.equal(invalidated.status,'returned');assert.equal(invalidated.invalidatedApproval,true);
  const approvalHistory=(await owner.query('SELECT approved_by,approved_at,return_reason FROM early_years_report_revisions WHERE school_id=$1 AND id=$2',[school,created.revisionId])).rows[0];assert.ok(approvalHistory.approved_by&&approvalHistory.approved_at);assert.match(approvalHistory.return_reason,/Evidence changed/);
  const revised=await post(`/early-years/reports/${created.id}/revisions`,{version:invalidated.version,correctionReason:'Update report to reflect the corrected observation evidence',strengths:'Joined a shared activity and took turns with peers after receiving a prompt.',nextSteps:'Continue offering opportunities to lead a short shared activity.',teacherNote:'Updated synthetic teacher note'});assert.equal(revised.status,'draft');
  const resubmitted=await post(`/early-years/report-revisions/${revised.id}/submit`,{version:1});const reapproved=await post(`/early-years/report-revisions/${revised.id}/approve`,{version:resubmitted.version});const published=await post(`/early-years/report-revisions/${revised.id}/publish`,{version:reapproved.version});assert.equal(published.status,'published');
  const visible=await (await call(`/guardian/children/${nurseryLearner}/reports`,'GET',undefined,guardian)).json();assert.equal(visible.items.length,1);assert.equal(visible.items[0].revision,2);assert.equal(visible.items[0].status,'published');
  const correctionDraft=await post(`/early-years/reports/${created.id}/revisions`,{version:published.version,correctionReason:'Correct a clerical issue in the published narrative',strengths:'Corrected narrative for guardian review.',nextSteps:'Continue offering opportunities to lead a short shared activity.'});assert.equal(correctionDraft.status,'draft');
  const stillPublished=await (await call(`/guardian/children/${nurseryLearner}/reports`,'GET',undefined,guardian)).json();assert.equal(stillPublished.items.length,1);assert.equal(stillPublished.items[0].revision,2);
  assert.equal((await call(`/guardian/children/${nurseryLearner}/reports`,'GET',undefined,guardian,other)).status,404);
  await owner.query("UPDATE guardian_links SET revoked_at=now(),revoked_by=$1,revocation_reason='Synthetic guardian report test ended',version=version+1 WHERE school_id=$2 AND id=$3",[headMember,school,linkId]);
  assert.equal((await call(`/guardian/children/${nurseryLearner}/reports`,'GET',undefined,guardian)).status,404);
});
